### PR TITLE
Add parsing of LyCORIS folder

### LINKED ISSUE #106: [FEATURE] Add new LyCORIS folder parsing
Could you parse the new folder dedicated to LyCORIS ?

New extension replacing previous Locon extension that mixed Lora & LyCORIS in a single folder :
[https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris)

It could include : parsing this directory & add helpers on new LyCORIS panel.

LyCORIS

### PR DESCRIPTION
**Pull request by goldmojo**
Add parsing of LyCORIS directory : ...\stable-diffusion-webui\models\LyCORIS

in order to support new extension => [https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris)

Fixes #106, #151 and #158

### CODE REVIEW

**Comment by CansecoDev** [comment]
This PR only cover thumbnails, for proper support it should also implement the features from the scanner/downloader/updater from the Cititai helper tab.

**Comment by CansecoDev** [comment]
The issue with this implementation is that it doesn't respect the `--lyco-dir` launch parameter, storing the models downloaded with the helper into the default directory, making scanner and updater also ignore the existence of models in the actual directory AUTO111 is using when a different path is set.

**Comment by goldmojo** [comment]
> lyco-dir

Thank you, I didn't notice this extra parameter. I will add this parameter.

**Comment by goldmojo** [comment]
> This extension won't support any other extension's feature. We only support SD webui's build-in feature.
> 
> Please keep this change in your fork.

Thank you for your answer.

Do you prefer I close this pull request or let it open for any interested user ?

**Comment by goldmojo** [comment]
Thank you @butaixianran for your answer.

Do you prefer I close this pull request or let it open for any interested user ?

**Comment by butaixianran** [comment]
A general rule for this kind of issue or pr are just put them there for a week. If no further response then close them.

**Comment by aleph23** [comment]
@goldmojo I should have checked here first, I just wrote (almost) the exact same thing and was going to pr it myself...

**Comment by ghostsquad** [comment]
So what's going on here? Is this not getting merged?

**Comment by ghostsquad** [comment]
> This extension won't support any other extension's feature. We only support SD webui's build-in feature.
> 
> Please keep this change in your fork.

Even if the feature is backwards compatible? (Meaning the other extension is installed or not installed, doesn't break anything)

**Comment by Lute-4** [comment]
Please merge it, this extension https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris is the main one to use the thousands of Lycoris that are on Civitai. :)

**Comment by yeungmozhu** [comment]
Creating a symbolic link from the LyCORIS folder to the Lora folder solves the problem for now.

**Comment by boredofnames** [comment]
@butaixianran  don't really understand the decision to not support LyCORIS when it's a part of, and supported by civitai. Could you explain the reasoning here?

**Comment by HaydenReeve** [comment]
This is a great feature and I was surprised to not see it implemented by default. Thanks for the fork I'll definitely be using this one over main.

**Comment by CamiKaa** [comment]
Civitai-Helper -> Civitai explicit asks you to install the lycoris extension so you can use these types of files on SD Webui -> Owner refuses to implement and support it

**Comment by anne43983959** [comment]
Due to LyCORIS's perfect compatibility with LoRA, LoCon, and LoHa, it can actually replace the built-in LoRA extension and solve the problem of WebUI modifications causing LoCon extension failure. Therefore, you can directly create a mapping called LyCORIS for the LoRA folder using "mklink" in the "models" directory. This way, all models can still be saved in the LoRA folder, but all can be called in the form of "<lyco:>".
This can perfectly address a series of issues caused by LoCon extension failures while maintaining the status quo of Civitai Helper extensions without losing any original functionality

由于LyCORIS具有完美兼容LoRA、LoCon和LoHa的特点，实际上它是可以代替内置的LoRA扩展并解决webui改动内置LoRA扩展引起LoCon扩展失效的问题。因此，可以在“models”目录下直接用“mklink”为LoRA文件夹建立一个名为LyCORIS的映射。这样依旧可以将所有模型都保存在LoRA文件夹内，但全部以“<lyco:>”的形式调用。
这可以在Civitai Helper扩展保持现状，并且不损失任何原有功能的情况下，完美应对LoCon扩展失效引起的一系列问题。

**Comment by ghostsquad** [comment]
Oh, I didn't know that LyCORIS is backwards compatible with LoRAs!

**Comment by tomyummmm** [comment]
> Due to LyCORIS's perfect compatibility with LoRA, LoCon, and LoHa, it can actually replace the built-in LoRA extension and solve the problem of WebUI modifications causing LoCon extension failure. Therefore, you can directly create a mapping called LyCORIS for the LoRA folder using "mklink" in the "models" directory. This way, all models can still be saved in the LoRA folder, but all can be called in the form of "lyco:". This can perfectly address a series of issues caused by LoCon extension failures while maintaining the status quo of Civitai Helper extensions without losing any original functionality
> 
> 由于LyCORIS具有完美兼容LoRA、LoCon和LoHa的特点，实际上它是可以代替内置的LoRA扩展并解决webui改动内置LoRA扩展引起LoCon扩展失效的问题。因此，可以在“models”目录下直接用“mklink”为LoRA文件夹建立一个名为LyCORIS的映射。这样依旧可以将所有模型都保存在LoRA文件夹内，但全部以“lyco:”的形式调用。 这可以在Civitai Helper扩展保持现状，并且不损失任何原有功能的情况下，完美应对LoCon扩展失效引起的一系列问题。

In case anyone else came across this issue. The workaround is as follows:

1. Shut down A1111 webui and console.
2. Move the LyCORIS folder into Lora, make sure no folder called LyCORIS exists in the models folder.
3. Open CMD as Administrator
4. Run the following command, replace `user` and path with your own accordingly: `mklink /D "C:\Users\user\Documents\stable-diffusion-webui\models\LyCORIS" "C:\Users\user\Documents\stable-diffusion-webui\models\Lora\LyCORIS"`

You should see the following:
`symbolic link created for C:\Users\user\Documents\stable-diffusion-webui\models\LyCORIS <<===>> C:\Users\user\Documents\stable-diffusion-webui\models\Lora\LyCORIS`

If you get the following error, read Step 1 properly.
`Cannot create a file when that file already exists.`


Now when you start A1111 webui again, Civitai Helper can scan the LyCORIS folder inside of Lora folder, and automatically download all information and preview image. At the same time, https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris can also see the LyCORIS link to the actual folder.

**Comment by goldmojo** [comment]
Checks each checkbox by default in "Check models’ new version" section for personal comfort

**Comment by Neverdusk** [comment]
Now that the Auto1111 main branch supports Lycoris / LoHa, can this be merged into the extension?

**Comment by tim9292654** [comment]
Now the latest version of a41 version 1.5, does not show the Civitai assistant additional button, this Civitai assistant additional button A1111 - the latest DEV version of WebUI broken, can it be fixed, although someone has fixed it, it does not support lycoris

**Comment by goldmojo** [comment]
Integrated to AAAA 1.5, closing the pull request and deleting the fork

**Pull request closed without merging**
