### PR TITLE
Fix issue #7 Does not work with custom model directory paths

### PR DESCRIPTION
**Pull request by williamkmlau**
Fix Issue #7 

- Changed to use data paths provided by SD shared module

### CODE REVIEW

**Comment by butaixianran** [comment]
You code won't work:
* shared.cmd_opts.ckpt_dir will be None if not offered in argurement. 
* You have not done any None check.
* path is joined with working root path, set full paths to model_folders won't work at all

Do not create pull request if you haven't viewed the code nor run a full test.

This pull request will be closed since it won't work.

**Comment by williamkmlau** [comment]
> You code won't work:
> 
> * shared.cmd_opts.ckpt_dir will be None if not offered in argurement.
> * You have not done any None checking.
> * path is joined with working root path, set full paths to model_folders won't work at all
> 
> Do not create pull request if you haven't viewed the code nor run a full test.
> 
> This pull request will be closed since it won't work.

Hey, I did test it and its working for me. 
I did not use embeddings and hypernetworks command line option.
I used lora and ckpt command line option.

image

image
image

**Comment by butaixianran** [comment]
On when scanning. For other funtions, it will merge root path with this path, then it won't work.

Like I said, if you haven't viewed the full code or did a full test, do not create pull request.

**Comment by butaixianran** [comment]
I've already tested these API with coding. This extension will handle this in the next version, you don't need to do anything.

**Pull request closed without merging**
