### PR TITLE
Allow use of alternate paths via the CLI.

### PR DESCRIPTION
**Pull request by dsully**
Also:

* Clean up module imports.

* Fix spelling.

* Remove unused variables.

### CODE REVIEW

**Comment by butaixianran** [comment]
This feature is already in the latest version, no need to merge.

**Comment by dsully** [comment]
It is not. Please look at your code, it's commented out at the top, and the models directory doesn't take into account the `--ckpt-dir` option.

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/main/scripts/civitai_helper.py#L68

Additionally, using `os.getcwd()` shouldn't be used, but instead `from modules.path import data_path`

**Comment by butaixianran** [comment]
What you mean it doesn't take into account "--ckpt-dir"

it already handled `ckpt_dir` as following:
```python
if shared.cmd_opts.ckpt_dir and os.path.isdir(shared.cmd_opts.ckpt_dir):
    model_folders["ckp"] = shared.cmd_opts.ckpt_dir
```

You mean this is not the right one to get ckpt folder?

**Comment by dsully** [comment]
It looks like you just merged your dev / local changes 22 minutes ago, as opposed to the hour ago when I made my change.

**Comment by butaixianran** [comment]
ok, so it is done.

**Comment by dsully** [comment]
Yes, thank you.

**Pull request closed without merging**
