### PR TITLE
correct path --data-dir

### PR DESCRIPTION
**Pull request by w-e-w**
current work directory is not the root "data" directory
see `--data-dir` [ Command-Line-Arguments-and-Settings](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings)

note currently there is a bug in webui <= [1.2.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/89f9faa63388756314e8a1d96cf86bf5e0663045) that will ignore `--data-dir` if it is set via `COMMANDLINE_ARGS`
this bug should be fixed in 1.3.0+

### CODE REVIEW

**Comment by butaixianran** [comment]
--data-dir is a bad command argument which nobody should use it.

won't support it

**Comment by w-e-w** [comment]
please explain why you think `--data-dir` is bad

the issue now with more and more extension is that it's getting very fragmented
web UI already have too many flags for paths
```
--ckpt-dir
--vae-dir
--hypernetwork-dir
--embeddings-dir
--lora-dir
--ui-config-file
--ui-settings-file
--styles-file
--bsrgan-models-path
--esrgan-models-path
--ldsr-models-path
--realesrgan-models-path
--scunet-models-path 
--swinir-models-path
--codeformer-models-path 
--clip-models-path
```
and this is not counting the ones added by extensions or the ones files that not available be configured

there is a need of keeping user data separated from the webui installation
particularly cloud installations and other cases that might involve multiple instances of web UI or just a general clean reinstall
some advanced users even run under different work directory

the main use of `--data-dir`
is to set the location of "every" user data at once
as opposed to 15+ different locations

**Comment by butaixianran** [comment]
sd webui is based on a very bad design, which put data folders and files into its root folder.

Then data-dir command argument will only set path for some of those folders and files. Which will cause a lot of problems in many extensions. 

If you search sd webui's issue list, you will find out even sd webui itself will have issues when using this command argument.

It's a command argument full of troubles and we won't support it. Please keep this in your own fork.

**Comment by w-e-w** [comment]
`--data-dir` was a new addition to webui 2 months ago, as it is relatively new not all extensions especially old ones don't support it. and yes there are some bugs, I even patched one myself couple of days ago

`--data-dir` is the method that AUTO has decided consolidate user data
in my opinion the idae of `--data-dir` itself isn't problematic, the problem was it was introduced too late to he project
do you have a better solution to the problem, if so please voice them, either to AUTO directly or here and I will relay them

ultimately you're the owner of the repo, it is your decision whether or not to follow upstream changes, the only thing we can do is respect your decision.

**Comment by butaixianran** [comment]
won't support this

**Pull request closed without merging**
