### PR TITLE
Configurable lora weights and trigger words

### PR DESCRIPTION
**Pull request by jokker87**
Hi butaixianran

I did an implementation of the above mentioned wanted feature. feel free to check it out and drop a feedback. guess we could extend this to the other types too.

Best regards

### CODE REVIEW

**Comment by butaixianran** [comment]
This is not the right way to do it. 

Also, this is a civitai extension, none civitai feature should not be included.

**Comment by jokker87** [comment]
what is the correct way to do it?

**Comment by butaixianran** [comment]
First of all, again, this is a civitai extension, none civitai feature should not be included.

Second, you are adding form to a card of a card list. There is no way any management system gonna design a form like this.

If you are using a form, then it's a part of management system. So it should follow all design principles of a management system.

**Comment by jokker87** [comment]
thanks for the reply, it's appreciated and i get your point. i'm surely not even a good ui designer too, just smashed something together. the ui i made is far from ideal.

**Pull request closed without merging**
